version: "3.9"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1  # enable more verbose logs
      - DOCKER_HOST=unix:///var/run/docker.sock #unix socket to communicate with the docker daemon
#      - LAMBDA_KEEPALIVE_MS=0 # disable lambda keepalive
      - LOCALSTACK_HOST=localstack # where services are available from other containers
      - ENFORCE_IAM=1 # enforce IAM policies
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  ls:
    name: ls
